services:
  - type: web
    name: getyouraccounts
    env: php
    plan: free
    region: oregon
    rootDir: .
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:xxxxxxxxxxxxxxxxxxxxx" # Remplace par ta clé Laravel
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
